artifact_location: file:///home/madfuckinman/Documents/python_dev/ml-workspace/OpenClassrooms_AI_Projects/Project_8/mlruns/0
creation_time: 1755008866771
experiment_id: '0'
last_update_time: 1755008866771
lifecycle_stage: active
name: Default
