name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jjobs:
  test:
    runs-on: ubuntu-latest
    env:
      # MLflow + S3 bucket configuration
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      MLFLOW_S3_ENDPOINT_URL: ${{ secrets.MLFLOW_S3_ENDPOINT_URL }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # SMTP Configuration
      SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_EMAIL: ${{ secrets.SMTP_EMAIL }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      SMTP_FROM_ALIAS: ${{ secrets.SMTP_FROM_ALIAS }}
      ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Project_7/deployment/api/requirements.txt
          pip install pytest

      - name: Run unit tests
        run: |
          pytest Project_7/deployment/api/tests

  build_and_push:
    needs: test
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./deployment/api
          file: ./deployment/api/Dockerfile
          push: true
          tags: yourdockerhubusername/sentiment_api:latest


